-- begin PASSKEEPER_NOTES
alter table PASSKEEPER_NOTES add constraint FK_PASSKEEPER_NOTES_ON_FOLDER foreign key (FOLDER_ID) references PASSKEEPER_FOLDER(ID)^
create index IDX_PASSKEEPER_NOTES_ON_FOLDER on PASSKEEPER_NOTES (FOLDER_ID)^
-- end PASSKEEPER_NOTES
